name: njsscan
on:
  push:
  pull_request:
  
jobs:

  temp_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Temp Step 1
        run: echo Temp 1

  nodejs_scanner:
    uses: ritik-deriv/njsscan-reusable-workflow/.github/workflows/nodejs-scanner.yml@main
    secrets:
      TRIVY_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      actions: read

  temp_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Temp Step 2
        run: echo Temp 2
